# Generated by Django 6.0 on 2025-12-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=100)),
                ('jenis_obat', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('tanggal_kadaluarsa', models.DateField()),
            ],
        ),
    ]
